### ISSUE TITLE
Favorites? Wishlist? Compare list?

### ISSUE THREAD

**Issue by Tonyno456** [papacarp/pooltool.io#1]
Make it even more user friendly! On my way to choose where to delegate, I chose a few pools as candidates, and after keeping track of each websites I thought that being able to flag them as my favorite ones directly on pooltool.io, and being able to see their specs side by side, would be a nice feature. 
Cheers mate!

**Comment by papacarp** [comment]
you can now favorite them so I'm closing this out.  side by side comparisons can now happen when multiple pools are favorited on the main page and you filter by favorites.
