### ISSUE TITLE
Feature request: Ability to edit Extended Metadata.json

### ISSUE THREAD

**Issue by steakandbake** [papacarp/pooltool.io#104]
Adapools.org released the ability to claim ownership of pools. https://t.co/dwCypYpPdi?amp=1
To do so, we must insert a specific string into the extended metadata.json file temporarily.
The ability to generally edit the extended metadata.json would be greatly useful for all SPOs.

**Comment by papacarp** [comment]
Yes, we are aware of this limitation.  We are planning to implement the standardized version of metadata for explorers that is slowly winding through the CIP process and have been holding off on modifying that section until that is done.
