### ISSUE TITLE
Feature Request: Subtotal of Favorite Addresses under Profile

### ISSUE THREAD

**Issue by RandyOlsen** [papacarp/pooltool.io#106]
Posting Here as instructed from the 'About' section of Pooltool's website.

Hi Mike, Gabor & Umed - or anyone reading this - thank you for all you do, I sincerely appreciate it.

Until there is multi-delegation support in Daedalus I have broken up my million ADA into 10 wallets for **the only reason** to support as many SPO's as I can around the world; by 100K delegation to each (LOVE, PEGA & SKY and 7 others).

**I have added the wallets as favorites and have the following request for consideration:
Under the Favorite Addresses section of the Profile page, request that there is a subtotal of all favorited wallets when selection is set to 'ALL', for the columns LifeTime Staking Rewards, LifeTime Stake ROS.**

This way I can see these KPI for my entire holdings, in addition to each wallet.

Currently I am using a google spreadsheet to track my portfolio performance in the aggregate.

Thanks

**Comment by papacarp** [comment]
Yes, this will be coming with the next major release of pooltool!
