### ISSUE TITLE
small mod to sendmytip.sh following cardano-cli update to 1.24.2

### ISSUE THREAD

**Issue by adrem1** [papacarp/pooltool.io#109]
Hi @papacarp,

I hope this finds you well. I have posted this on the Cardano Forum (https://forum.cardano.org/t/sendmytip-sh-slight-mod/43302) and both Priyank and COSD suggested posting it here. I am not confident enough with Github to make a pull request and this is only a very small issue. Apologies for that.

- While doing some log checking I noticed that the log for sendmytip was returning a message asking to move Shelley sub-commands to the top level (as described in the release notes for 1.24.2).

- In response to this I took the liberty to modify line 38 of the sendmytip.sh script like so:

- alias cli="(which cardano-cli) shelley" ---> alias cli="(which cardano-cli)"

- This fixed the Warning.

COSD also suggested that for those running this as a systemd service, a similar change should occur at line 40 of the code. 

Please let me know if you need more information, and thank you for your time.

Cheers,

A

**Comment by gacallea** [comment]
@adrem1 thanks for this.
@papacarp I have "taken care" of it, if you like the changes: https://github.com/papacarp/pooltool.io/pull/110

**Comment by adrem1** [comment]
@gacallea Grazie mille a te!

Thank you both for your time and dedication!

Cheers,

A
