### ISSUE TITLE
Feature request: Adversarial fork history

### ISSUE THREAD

**Issue by Straightpool** [papacarp/pooltool.io#11]
It would be great if pooltool.io would keep track of the adversarial fork history for the last 24 hours or so to compare against the blockheights of our restart scripts to see if they match.

**Comment by papacarp** [comment]
Yes!  I've been hoping to get the full history (the last 5000 blocks) into pooltool.  But not sure its going to happen today and I'm travelling first half of next week.  So...  here is the raw data?  You can always get the latest from this link (updated once a minute):  https://pooltool.s3-us-west-2.amazonaws.com/stats/forkers.json

And just for completeness.  the getTips is also in a json, updated once a minute if that helps your scripts.

https://pooltool.s3-us-west-2.amazonaws.com/stats/stats.json
