### ISSUE TITLE
If you have multiple relays, what latency appears on network health tab?

### ISSUE THREAD

**Issue by stanfieldr** [papacarp/pooltool.io#111]
Assuming PT_MY_NODE_ID is set correctly on each node, is it the faster one that appears?
![image](https://user-images.githubusercontent.com/7494573/102716942-18eea300-42ad-11eb-8a16-c8fb7465fef7.png)

**Comment by papacarp** [comment]
you can only send in one tip per pool right now.  so if you are sending in multiples, whatever the most recent value is will get saved.
