### ISSUE TITLE
Reinstated retired pools still show as retired.

### ISSUE THREAD

**Issue by stormrage-neilr** [papacarp/pooltool.io#113]
I was retiring my pool but had a change of heart when it produced its first block. However, not it's still showing as retired in pooltool.io. 

Pool ID: 412ddc857057bfcd4e501f2e7f8656ff3f8136f1239a1b063d543f98

**Comment by papacarp** [comment]
fixed up for  ya, and closed out

**Comment by stormrage-neilr** [comment]
Many thanks Mike!
