### ISSUE TITLE
Mobile App Enhancement Idea

### ISSUE THREAD

**Issue by kairosway** [papacarp/pooltool.io#116]
Would be nice to see a avg. epoch returns rate in terms of **avg epoch total** # ada on the Rewards tab, perhaps under the total reward header.  Also curious what you are planning to do to display yht bar chart when the number of epochs increases over 30, you an only make those bars so thin, perhaps you can have a default limit of 20 epochs (100 days), and the ability to scroll left to see more of your historic rewards. Just some thoughts :)

**Comment by papacarp** [comment]
we did something like this on pooltool.io.  let us know what you think, it would be pretty easy to add to the mobile app.
