### ISSUE TITLE
error getting leaderLogs

### ISSUE THREAD

**Issue by adrem1** [papacarp/pooltool.io#117]
Hi all,

I am attempting to get leaderLogs for my pool. Getting the sigma value works perfectly, but then, when running leaderLogs.py I get a 

[WARN]: Unable to fetch data from epoch API
[ERROR]: One or more arguments are missing or invalid. Please try again.

In my command I specify --vrf.skey --sigma and --epoch. Is it possible that this happens because of permissions on the vrf.skey file?

**Comment by adrem1** [comment]
Sorry for double posting,

I have queried the API in a web browser and used the --epoch-nonce and --d-param specified there. Now the script still returns the [WARN] above, but not the [ERROR]. I guess me not being able to query the API was causing key parameters to not be parsed. Any ideas why I may be unable to query the API?

**Comment by papacarp** [comment]
Sounds like you are not able to get the nonce from Adam’s api endpoint.  We
should check and see if something changed on his end.  In the meantime have
you considered using cncli?

**Comment by adrem1** [comment]
hi Mike, 
thank you for your feedback. I don't mind querying the API 'manually' and passing all the info over this way. I have done it a handful of times now, and it works. Could my inability to query the API be due to firewall rules?

In regards to cncli, I apologise if this sounds a bit backwards, but I like to do things manually. Many people have told me it would make my life quicker and easier, I just haven't gotten around to make that leap. Thank you for the suggestion!

Let me know if I can assist with the API investigation.

Best,

A

**Comment by adrem1** [comment]
Hi @papacarp,

thank you for updating the leaderLogs.py script to the new API. As you may recall I was having some issues with the old one, no all good: works a treat.

Thanks again,

A
