### ISSUE TITLE
Issue: Rewards Data Pool is missing Epoch 249 and 250 / Rate and Price 

### ISSUE THREAD

**Issue by lodl** [papacarp/pooltool.io#122]
In the Rewards Data for Taxes the Pool Names of the last two Epoch 249 and 250 is missing. Also the Rate and Price of the Token. 

Here is an Random Example: https://pooltool.io/address/5a36970fe7610eab2e91ffb0c50114781ab23d2c9a754c63bb6becf6

Anyway, thanks for your great work! 

![image](https://user-images.githubusercontent.com/44868882/109609926-559c0d80-7b2c-11eb-87b3-f2fa7090e5f9.png)

**Comment by papacarp** [comment]
Ok, a few loose ends to clean up tomorrow.  thank you.

**Comment by papacarp** [comment]
fixed!
