### ISSUE TITLE
Ticker not showing

### ISSUE THREAD

**Issue by stormrage-neilr** [papacarp/pooltool.io#125]
Hi,

I was having issues with my pool (Ticker : ZERO) so I retired it and created a new one from scratch. Only friends and family were delegating anyway. However now my ticker isn't showing on pooltools now for my new pool. I didn't want to bother you and was just hoping that it would update itself when the retirement completed but now I'm being asked by others if the ticker is available.

Will you please put my new ZERO pool on your site so noone else takes the Ticker?

Happy to send some ADA from the owner wallet address as proof if needed.

3c57cc6b808280758b369d694285db1a0fcb420a4b5cc5f363c3657d - retiring pool 078fb5ceaa78ef2939174efeee13b094720d5293bdc1181ac4bc5def - new pool

Thanks,
Neil

**Comment by papacarp** [comment]
please fix your metadata:

https://pool.vet/#078fb5ceaa78ef2939174efeee13b094720d5293bdc1181ac4bc5def

**Comment by stormrage-neilr** [comment]
My bad, thanks a lot MIke
