### ISSUE TITLE
sendmytip.sh

### ISSUE THREAD

**Issue by glitch40** [papacarp/pooltool.io#128]
Sendmytip script is no longer working with the latest pending version of the node 1.26.x

{"message": "Internal server error"}

reports not being sent out to pooltool node now appears offline

**Comment by gufmar** [comment]
do you have updated cncli to 1.51.1 ?

**Comment by glitch40** [comment]
Not using cncli using sendmytip.sh from https://github.com/papacarp/pooltool.io/blob/master/sendmytip/shell/sendmytip.sh

Not the send slot script

**Comment by glitch40** [comment]
Figured out the issue:

Original:

        nodeTip=$(cli query tip --mainnet)
        lastSlot=$(echo ${nodeTip} | jq -r .slotNo)
        lastBlockHash=$(echo ${nodeTip} | jq -r .headerHash)
        lastBlockHeight=$(echo ${nodeTip} | jq -r .blockNo)




1.26.1 changed to:

        nodeTip=$(cli query tip --mainnet)
        lastSlot=$(echo ${nodeTip} | jq -r .slot)
        lastBlockHash=$(echo ${nodeTip} | jq -r .Hash)
        lastBlockHeight=$(echo ${nodeTip} | jq -r .block)
