### ISSUE TITLE
(2) 0.95% fees show up differently, one as 1.0% and the other as 0.9%

### ISSUE THREAD

**Issue by lovelypool** [papacarp/pooltool.io#13]
Lovely Pool (0.95% fee, 95/10000) shows up as a 1.0% fee.
Lovely Pool 2, same fee as above, shows up as a 0.9% fee.

**Comment by lovelypool** [comment]
Correction, Lovely Pool had a 1/105 tax ratio, whereas the 2nd pool had 95/10000.  Sorry for any confusion.

**Comment by papacarp** [comment]
ok.  closing this then
