### ISSUE TITLE
Typo: recieves

### ISSUE THREAD

**Issue by ggreif** [papacarp/pooltool.io#133]
<img width="888" alt="Screenshot 2021-05-30 at 14 17 52" src="https://user-images.githubusercontent.com/1312006/120103859-f57c2e00-c151-11eb-981d-b3ddee7da261.png">

**Comment by rbacquie** [comment]
How is this improved

**Comment by ggreif** [comment]
`s/recieves/receives/g`
I don't have access to the GitHub repo, so I cannot submit a PR.

**Comment by papacarp** [comment]
cool.  translation issue.  fixed it up.  thank you
