### ISSUE TITLE
Clarify saturation curve annotations for endusers

### ISSUE THREAD

**Issue by Straightpool** [papacarp/pooltool.io#137]
**Summary**
Currently the saturation curve page has the following graph annotation for k = 1000:  "k = 1000 (Summer 2021???)". As we are in the middle of summer 2021 and k is unlikely to change anytime soon if ever, this annotation is confusing delegators.

**Steps to reproduce**
1. Go to pooltool.io
2. Open any pool detail page
3. Open tab "Saturation Curve"
4. See k = 1000 annotation on top of graph

**Expected behavior**
The k values should be clear to end users.
Proposal:
- change "k = 500" to "k = 500 (current)"
- change "k = 1000 (Summer 2021???)" to  "k = 1000 (possible future end state, not confirmed yet)"
- change ordering of the annotations, the k = 500 annotation should come first, k = 1000 second.

**Screenshots and attachments**
![image](https://user-images.githubusercontent.com/42584250/123642636-d097db00-d823-11eb-9b8f-453aca5f9110.png)

**Comment by papacarp** [comment]
releasing today
