### ISSUE TITLE
Feature Request: Support CoinTracker.io CSV export

### ISSUE THREAD

**Issue by ct-taylor** [papacarp/pooltool.io#139]
Would you be open to adding the [CoinTracker.io CSV export format?](https://help.cointracker.io/en/articles/5172429-converting-transaction-history-csvs-to-the-cointracker-csv-format) I've also attached a sample CSV. 

Thank you!
[cointracker_csv_import_v4.csv](https://github.com/papacarp/pooltool.io/files/6827717/cointracker_csv_import_v4.csv)

**Comment by michaeljfazio** [comment]
This would have been damn helpful for me this tax year. I've completed it manually for now. Really wish all these exchanges would make more of an effort to standardise on accounting formats!

**Comment by papacarp** [comment]
changes pushing up now.  please review and let us know if you have any feedback.

**Comment by ct-taylor** [comment]
This is great @papacarp! Thank you. I tested the CSV upload and it works great on CoinTracker. 

Only two super small nits:
1. CoinTracker is styled with the capital T
2. This text is now incorrect: "At this time we only support a generic csv out put or CoinTracking.info." 
 It could be changed to something like "At this time we support generic CSV output as well as CSV formats for Cointracker.io, CoinTracking.info, and CryptoTaxCalculator."

Thanks again!
