### ISSUE TITLE
Introduce Night Mode

### ISSUE THREAD

**Issue by nocturnal86** [papacarp/pooltool.io#14]
Just an idea to introduce a Night Mode for the site, since white pages are annoying for many users' experience, especially at night.

Thank you.

**Comment by papacarp** [comment]
Its not saving as a user preference yet, but its out there now
![image](https://user-images.githubusercontent.com/11194546/73316372-88682980-41e7-11ea-9290-e964e19ef2d3.png)

**Comment by papacarp** [comment]
night mode persists!
