### ISSUE TITLE
Feature Request: Support cryptotaxcalculator.io as a CSV option

### ISSUE THREAD

**Issue by timbrunette** [papacarp/pooltool.io#140]
CTO from CryptoTaxCalculator here
We've got a lot of users who are wanting us to integration with your CSV export to get the pool staking rewards. We've been able to integrate with your 'generic CSV' option and are in final stages of being able to release this.

Can you please add cryptotaxcalculator.io to your list of options? You can just map this back to the generic CSV option so minimal work on your end.

**Comment by papacarp** [comment]
changes for this are pushing up now.  Please review and let us know if you have any feedback.

**Comment by timbrunette** [comment]
@papacarp that looks good, i've tested and all seems to be working, this is it on our end. Thanks for your help!
![image](https://user-images.githubusercontent.com/36954990/128794283-7be4c294-a6cf-44a3-9c4a-a3bebc93a2fc.png)
