### ISSUE TITLE
Is Testnet version no longer avalable?

### ISSUE THREAD

**Issue by nori-crypto** [papacarp/pooltool.io#142]
Thank you for providing a nice tool.

Is Testnet version no longer avalable?
It shows block at May 31st is the latest block.

![2021-07-28](https://user-images.githubusercontent.com/86654122/127251784-9e8ebc27-599d-46b4-b9cd-d097dca82e25.png)

**Comment by papacarp** [comment]
yep, stopped supporting it awhile back due to cost.
