### ISSUE TITLE
Rewards data for taxes lost after claim?

### ISSUE THREAD

**Issue by chriswill** [papacarp/pooltool.io#144]
I claimed my stake address by sending the ADA amount, and this is appearing correctly.  I can also see my rewards data from the most recently paid epoch.  But is all of the past data lost?  I did not download it because there was no announcement that the data was going to be inaccessible.

**Comment by papacarp** [comment]
yea, past data is all available as well.   There should be a LOAD MORE button that will get you previous epochs data.

**Comment by chriswill** [comment]
@papacarp thanks but that doesn't seem to work.  When I click the blue Load More Data button it turns grey, but appears to do nothing else.  I clicked it and have waiting hours, but no update to the page.
