### ISSUE TITLE
 Signed up for an account and paid and can't log in

### ISSUE THREAD

**Issue by edmquintela** [papacarp/pooltool.io#145]
Hi,
I'm having the same issue than  #143 
It's been more than two hours since I sent the payment and still can't login

Address:
stake1u8uu3hjmctlhsux0wruak06y406ry72c2e5j7tczxamd3wsuyzpus

Message is:
"Account not found or password incorrect."

Please help!

**Comment by papacarp** [comment]
your account looks to be in good shape now.  Please check and let me know if there are any further issues.

**Comment by edmquintela** [comment]
Super duper. Authentication is working now, thanks!
The only issue now: only last two epoch rewards are showing.
Is there any way you can fix this so that I can see all the rewards ?
I intend to use this data for my tax report.

**Comment by papacarp** [comment]
You should be able to load the remaining epochs data using that "load more
data" button?

**Comment by edmquintela** [comment]
Ok, thanks for the follow up.
I tried clicking the "Load More Data" button: didn't change anything.
I tried it on Chrome and Firefox, latest version of each.
Here is what I see.
You'll notice that epochs 276, 277 and 287 are not showing at all.
![image](https://user-images.githubusercontent.com/22100227/131375872-c8193548-95b1-4cd4-b4a5-7b83bc26bc65.png)
