### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by galaxyart2021** [papacarp/pooltool.io#147]
How long does it take to verify my address?  I have sent two txn so far, one to setup and another to change the password since it wouldn't let me loging after sending the first.
Txn 1: 08aca0064f8bbb28bbea68d7fb9d6b1686cc96700564aebaa3d5de957ba76f5a
Txn 2: 42703a14e712f660dc17f87fe6d22260b2cb2887ac4b7635462194e2a1e61ce6

my address: addr1q926zhgyc3j3p7qgjjh9ju6gfqx50fgnkanx7rq063r9tuspghlz4sscxuczvq80ud0tqmvpqkx0xllz6zpsr2hrxmasrxz9w8
I sent 1.886000 ADA the second time with a fee of 0.168273
sent 1.146000 ADA the first time with fee 0.168273

Why can't I login to pooltool.io?

**Comment by papacarp** [comment]
I just looked at your account seems fine.  The first verification
transaction you did worked and you should be able to login.

**Comment by cordillera19** [comment]
I have the same issue.  I sent two transactions on 8/29 and still cannot log into the apps.  Here are the transaction IDs
880ef5afcffd50ce8c0bf112e2a57074ce1cb9fe3e3aa51f2571cfb70036b01f
b6378bb160ad6b77ea389a6eb6f1e9c3b9f9da548a9478590f4ec21963b1c23d

**Comment by Rblack77** [comment]
My login does not work.... I also sent the 1.97 transaction fee to the address specified and I can't make any progress. 
My address is as follows:   stake1u9pg5s9yyksvuv6u9ruyj45j6h5hg0asypzeyafvzm95dnsq62kdm
One more thing - do I need to have the account to get all of the information with respect to rewards in Canadian dollars. At this time when I download the "CSV" file it does not include this information.

**Comment by papacarp** [comment]
assuming this was taken care of?  if not feel free to reach out on telegram or here and I'll re-open it.  I'm just cleaning up old issues here.
