### ISSUE TITLE
Show which node version a given pool is running

### ISSUE THREAD

**Issue by fabiomolinar** [papacarp/pooltool.io#148]
Use case: I wanted to see if the pool I stake at has the version 1.29 that supports smart contracts because I want to make sure the pool I support also supports the project. 

Request: add the node version a pool is running to the pool stats page.

**Comment by papacarp** [comment]
we decided long ago not not include node versions unless its already on the blockchain.  for reporters it can be an attack vector as we get specific node versions and even hashes so attackers could know precisely if a node is running a given codebase.  we only supply this data in aggregate.
