### ISSUE TITLE
Retired pool is back and is not marked as active again [ITFX]

### ISSUE THREAD

**Issue by tevkar** [papacarp/pooltool.io#152]
It has passed many hours and the change is not reflected at pooltool.io (Adapools and Cardanoscan are ok).

**Comment by andreabravetti** [comment]
I'm having the same problem with my pool GOADA (a0a4ff7435e58f9435760cb950371671cec3dd094e439745c8f75fe3).
It was retired but now it's registered again and is online, even if we need to add pledge and make a proper launch.
I had the same problem with adapools and they fixed it immediatly.
What is nice is that pooltool has updated metadata and everything seems to be ok, except the retired flag.

**Comment by andreabravetti** [comment]
@papacarp is there any way to mark a pool that was retired but now is back online as active?

**Comment by papacarp** [comment]
both are fixed
