### ISSUE TITLE
Feature Request: Display Slot/Height Battle History for Pools

### ISSUE THREAD

**Issue by orpheus-antpool** [papacarp/pooltool.io#154]
There is no easy way to figure out what happened with the orphaned blocks or when the pool is on the winning end of slot/height battles, unless all accepted and orphaned blocks are manually explored.

As an improvement, instead of displaying orphaned blocks, it is more useful to display the whole slot/height battle history (with the option of filtering by winner, loser or both).

**Comment by papacarp** [comment]
in latest version, you can link to battle history
