### ISSUE TITLE
Feature Request: Support Koinly.io CSV export

### ISSUE THREAD

**Issue by Manufacturing1** [papacarp/pooltool.io#156]
Hello,
I came across pooltool.io though searching for sites that can export ADA pool staking rewards in a csv. I am using Koinly.io to do my taxes but did not see it as an csv export option. I modified an existing export formatting into the koinly 'Universal Format'. For reference: ([https://help.koinly.io/en/articles/3662999-how-to-create-a-custom-csv-file-with-your-data](https://help.koinly.io/en/articles/3662999-how-to-create-a-custom-csv-file-with-your-data))

Here is an example csv import that worked for me. 
[koinly_csv_import.csv](https://github.com/papacarp/pooltool.io/files/7876308/koinly_csv_import.csv)
 
Also, I created a GitHub account just to say thanks for creating that site and I wanted provide this feedback for further improvements.

**Comment by papacarp** [comment]
ok, thank you.  Looks easy enough to implement.  I'll add it to the list of
things to implement

**Comment by vietqhoang** [comment]
Just want to put a +1 to see this feature implemented.

Thanks for the great contribution.
