### ISSUE TITLE
CNCLI - pointing to depreciated repo

### ISSUE THREAD

**Issue by futuristudios** [papacarp/pooltool.io#164]
andrew changed where cncli lives from under his profile [https://github.com/AndrewWestberg/cncli](https://github.com/AndrewWestberg/cncli) to [https://github.com/cardano-community/cncli](https://github.com/cardano-community/cncli).

on pages such as [https://pooltool.io/networkhealth](https://pooltool.io/networkhealth) the link is pointing to the depreciated repo.

**Comment by papacarp** [comment]
if you are referring to logging in you need to use any of your stake
addresses assuming you have an account in our system
