### ISSUE TITLE
Rewards not displayed

### ISSUE THREAD

**Issue by ErikSlevin** [papacarp/pooltool.io#167]
the last 3 epochs (359,358,357) the rewards are not displayed.

**Comment by papacarp** [comment]
Find your address on the Pooltool website. Then they will show up on the
mobile app as well. We have an update in process for the mobile app.

**Comment by ErikSlevin** [comment]
No rewards displayed since epoch 360.

Epcohe 360: Rewards calculated but not included in Total Rewards
Epoch 361: nothing
Epoch 362: nothing

The last epoch I am shown is epoch 362 from September 18th 2022, 12:03:00 AM. After that there is nothing.

Tried via Chrome, Edge, Firefox with Windows 11 and via Mobile.

**Comment by papacarp** [comment]
Rewards are displaying fine for all registered accounts. Feel free to DM me
your stake key and I’ll check on your account.

**Comment by papacarp** [comment]
Hi Erik, we found an issue that affected some accounts.  fixed it in latest release.  I'm guessing thats why you could not see rewards.  closing this issue for now.  lmk if not addressed.
