### ISSUE TITLE
Need a way to close pool detail panel

### ISSUE THREAD

**Issue by hodlonaut** [papacarp/pooltool.io#17]
Load up pooltool.io
Click a star icon next to some pools
Change pool filter criteria to see a different set of pools
Click a star icon next to some pools

Pool details panels at the bottom just keep on accumulating

If they're meant to act as a favorites list of some sort, then need a way to easily close them (without having to search for that pool again in the pool list and unticking the star)

If they're meant to act as just 'show details' panel, then should probably disappear whenever the pool they're referencing is no longer mentioned in the shown-to-user pool list

**Comment by papacarp** [comment]
I modified how these work so you can have favorites and also sort on favorites
