### ISSUE TITLE
Legend for Orca/Beluga is switched

### ISSUE THREAD

**Issue by nilscodes** [papacarp/pooltool.io#172]
I assume Beluga and Orca categories are correctly ordered, but the legend below them is incorrect.

Beluga would be 50k-100k
Orca would be 100k-5mil

![image](https://user-images.githubusercontent.com/2282558/197371622-6224083b-ed5c-425c-821f-c557d052d180.png)

Keep it up!

**Comment by papacarp** [comment]
indeed.  fixed up, changes will get pushed to production server sometime today.  Thank you for the report.

**Comment by nilscodes** [comment]
Now there is a gap between Orca and Sperm whale ^^

**Comment by papacarp** [comment]
Looks ok to me, what am i missing?  argh!
![image](https://user-images.githubusercontent.com/11194546/200626668-d86c1e02-00d4-4f18-877b-6f2f8315df76.png)

**Comment by papacarp** [comment]
if you don't have any in a range it doesn't show it.  for example see below.  is that what you mean?
![image](https://user-images.githubusercontent.com/11194546/200626971-70e1947b-a5bb-4dc9-a857-defa4e4dc8d2.png)

**Comment by nilscodes** [comment]
That could explain it indeed :) Wasn't aware that it only shows the categories one has in the pool! Thanks :)
