### ISSUE TITLE
Add epoch # column to the pool detail view

### ISSUE THREAD

**Issue by hodlonaut** [papacarp/pooltool.io#19]
Currently we show number of blocks minted, rewards etc but are showing a list without 'epoch #' column - such a column would be a nice one to have.

Also would be nice to show all epochs for now or at least last 25-50 (if there aren't any performance issues associated with fetching that informaton)

**Comment by hodlonaut** [comment]
Also, ROI calculation for the epoch would be handy on this page too as a last column - to save me trying to do mental arithmetic and fail 😭

**Comment by papacarp** [comment]
This is finally done. :)  If you click on the ticker you will see the full details by epoch.  I'm going to be removing the details when you click the star down below in favor of pool specific pages.
