### ISSUE TITLE
Feature Request: show all own node stats on profile page

### ISSUE THREAD

**Issue by marimes** [papacarp/pooltool.io#20]
My typical workflow includes refreshinghttps://pooltool.io to get updated header stats, then typing "ko" in the search box to find my pool _Kontiki_. 

This feature request is for a one-click method to see the stats for my node:
- show updated stats on https://pooltool.io/profile; OR
- preserve the search term between sessions

**Comment by papacarp** [comment]
favorites added so you can get to yours fast.  I'll persist sort order soon too.  hopefully that addresses this!
