### ISSUE TITLE
RoS Not accurate??

### ISSUE THREAD

**Issue by AWCrypt** [papacarp/pooltool.io#23]
Hi PapaCarp :)

So far our RoS from staking to our own pool is 11.7% over 55 epochs, but it's showing as 8.1% on PoolTool.

Not sure where the PoolTool numbers come from or in which epoch they began etc but not accurate for everyone :)

**Comment by papacarp** [comment]
Ok.  So lifetime ROI.  Can you show me your math so I can compare with mine?

**Comment by AWCrypt** [comment]
Yes.
The math is:
Started pool with 67499 staked to it
Stake + staking rewards is now up to 68667
:)

**Comment by papacarp** [comment]
Ok :), I mean how do you get to 11.7%

**Comment by AWCrypt** [comment]
oh ok :)

1) 68667 - 67499 = 1168 = 54x epochs of rewards (if in 55th epoch rewards for 55-1 = 54 epochs).
2) 1168 / 67499 = 0.0173 = % gain in 54 epochs
3) 0.0173 x (365 / 54) = 11.7% = Annualised RoS

Q.E.D :)
