### ISSUE TITLE
Feature Request: Pool page refresh

### ISSUE THREAD

**Issue by lunarpool** [papacarp/pooltool.io#25]
It would be great to get some data refresh to pool detail page. I'm sometimes tracking Epoch log and the number of blocks in current epoch (header of the page) so would appreciate it.

Currently you need to refresh the page manually, set up night mode, switch tab, ... which is annoying.

**Comment by papacarp** [comment]
very annoying.  I agree.  need to get preferences saved.

**Comment by papacarp** [comment]
this is done
