### ISSUE TITLE
Feature Request: Expected number of blocks

### ISSUE THREAD

**Issue by lunarpool** [papacarp/pooltool.io#26]
It would be great to provide number of blocks expected for the stake in current epoch. So the delegator can see BPE, Epoch Blocks nad Expected Blocks all together, this could be interesting as to give basic picture in what is expected and where the pool is in current epoch.

But you would probably need to provide epoch stake as well to avoid confusion with Live Stake or maybe not and explain it in the column header tip.

adapools.org shows this number as "Estimated daily blocks" in the header of pool details page.

**Comment by papacarp** [comment]
Yes.  Blocks for my own pool vary widely - for a given stake, the blocks assigned can vary up to 50% so I'm a little uneasy putting it in there for each pool.  I'd rather accept block assignments from each pool and display that instead.  The trick is doing it in a way that gaming the system does not pay off.   Good feedback.  thank you
