### ISSUE TITLE
Pool search filter needs slight improvement

### ISSUE THREAD

**Issue by hodlonaut** [papacarp/pooltool.io#28]
If I type in AAA into the search field it should always do a search against a ticker symbol first, pool description next and only as a last resort look inside the pool GUID. 

Currently I'm not sure what the ordering is (if there is), but I see ZZZ pool listed first, some 1PCT pool third and Pal's UNDR pool fourth -instead of my three AAA pools.

**Comment by papacarp** [comment]
yea, it does a full text search on ID, ticker and name of the POOL.  so it comes up with everything.  I think we need select boxes for what type of search to do and to default to ticker only perhaps.  good feedback.  thank you.

**Comment by bergr01** [comment]
*bump*

**Comment by hodlonaut** [comment]
Closing as we have by-ticker search option now
