### ISSUE TITLE
Block height for a stake-pool not increasing when using filter

### ISSUE THREAD

**Issue by mark-stopka** [papacarp/pooltool.io#3]

**Comment by papacarp** [comment]
Hi Mark.  I haven't been able to duplicate this so long as the graphql is operational and talking to the server.  However I have seen that the graphql connection gets lost occasionally and has to be reloaded.  thats a background issue I need to address.  perhaps we rename this issue to "lost graphql connection requires reload of pooltool"

**Comment by papacarp** [comment]
closing this out as height does load when using filter.
