### ISSUE TITLE
send_slots.sh - error line 18: [: missing `]'

### ISSUE THREAD

**Issue by adosiawolf** [papacarp/pooltool.io#36]
when executing send_slots.sh the following error is produced:

line 18: [: missing `]'

which corresponds to the conditional:
if  [ -z "$MY_POOL_ID"] || [ -z "$MY_USER_ID" ] || [ -z "$THIS_GENESIS" ] || [ -z "$KEY_LOCATION" ]

the script continues to execute and performs as expected

**Comment by Mixxaz** [comment]
Has been corrected in current version of the script.
