### ISSUE TITLE
Sending slots fails

### ISSUE THREAD

**Issue by amani1104** [papacarp/pooltool.io#39]
Sending slots through the send_slots.sh script currently fails with the following error message: 

```
Everything ok. Starting ...
Packet Sent:
...
{"success": false, "message": {"error": "We were unable to parse the decrypted json data.  That either means we were unable to decrypt it, or the json is not valid"}}
```

**Comment by papacarp** [comment]
Hey, so it could be a lot of things.  I guess to sort it out we would need
to take a look at whatever you submitted, and your keys, and stuff to see
where things are broken.  Can you find us here so we can help?
https://t.me/pooltool

**Comment by papacarp** [comment]
closing this out assuming its taken care of.  If not, feel freel to reach out on telegram.  we have 140 pools submitting slots now so we can help!
