### ISSUE TITLE
Feature Request: Claim and hide pools we created by mistake

### ISSUE THREAD

**Issue by aftershowrc** [papacarp/pooltool.io#4]
Firstly, love the tool! keep it up. 

I know myself and a few others messed up our pool cert registrations (wrong fees) and other doohickys... But unfortunately those pools certs were sent to chain and we can't unregister them.. And now every time someone searches our tickers it is very confusing which one is the correct/operating one. 

So it would be great to have an option to claim (and validate ownership) of a pool and choose to hide it if desired in pooltool. The ownership validation might be tricky but it would nice to explore if it's possible. 

Thanks!

**Comment by papacarp** [comment]
i need to validate pool owners to allow this to happen.  I have some ideas on how to do this.  I'm also going to allow  you to add notes for delegators and communications through pooltool.  That might  help too.
