### ISSUE TITLE
Display the uptime of the stake pool. 

### ISSUE THREAD

**Issue by thibautrey** [papacarp/pooltool.io#41]
When my pool only had 300-500k delegation, a bunch of people asked me if my pool was still alive because I did not have any blocks. 

Assuming the different scenarios with either one or more nodes, it would be interesting to display the current and average uptime of the node. This could be a measure of the stability of the pool and if someone is considering delegating to a smaller pool, they can be reassuring it is real and alive.

**Comment by papacarp** [comment]
done :)

**Comment by thibautrey** [comment]
awesome. Well done ;)
