### ISSUE TITLE
Block trend enhancement

### ISSUE THREAD

**Issue by hex-pool** [papacarp/pooltool.io#8]
The block trend is confusing - if a pool suddenly loses a large delegator, it will be assigned less blocks and the trend will go down even if pool performance stays the same. This can give the wrong impression that the pool is not performing properly. 

The indicator would be more useful if it reported the percent of created blocks vs assigned blocks (average assigned blocks per stake)

**Comment by papacarp** [comment]
Thank you for posting here.  Ok, I agree with this.  I'll make the block trend neutral color so it only indicates blocks, not good or bad.

**Comment by papacarp** [comment]
A nice soothing blue
![image](https://user-images.githubusercontent.com/11194546/71786944-699abc80-2fc6-11ea-8844-f855fa838685.png)
