### ISSUE TITLE
Feature request: Download CSV from reward wallets info for tax purposes.

### ISSUE THREAD

**Issue by CreekWalker** [papacarp/pooltool.io#89]
I love the reward feature

One thing that would make this golden is export (rewards only) with CSV format.
To be used for tax purposes on sites like Koinly, Contracker etc...

![bild](https://user-images.githubusercontent.com/71961765/94359368-1530f300-00a7-11eb-9d0e-6981c7a3a389.png)

You could download a CSV from crypto_com for reference of how it should look like inside.

**Comment by molecular** [comment]
I need this!

**Comment by molecular** [comment]
for those that can't wait, here's a quick bash-hackjob that gets the json data from pooltool using curl and transforms it to csv using jq:

```bash
#!/bin/bash

staking_address="f46a6908e1605ed759c9bf8e7376f8cbf398b5259b8bd04b29c8a9a8"

function download() {
	curl -s \
	'https://gql.pooltool.io/v1/graphql' \
	-H 'Accept: */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' \
	--compressed \
	-H 'content-type: application/json' \
	-H 'Origin: https://pooltool.io' \
	-H 'Connection: keep-alive' \
	-H 'Pragma: no-cache' \
	-H 'Cache-Control: no-cache' \
	-H 'TE: Trailers' \
	--data-raw '{"operationName":"MyQuery","variables":{"address":"'${staking_address}'"},"query":"query MyQuery($address: String = \"\") {\n  pt_addresses_history(where: {stake_address: {_eq: $address}}) {\n    id\n    epoch\n    stake_address\n    operator_rewards\n    poolid\n    stake\n    stake_rewards\n    fcp1_stake_rewards\n    fcp1_operator_rewards\n    rewardssentto\n    rewardaddr_details\n    ptepoch {\n      ada_prices\n      reward_date\n      __typename\n    }\n    topoolticker {\n      ticker\n      __typename\n    }\n    __typename\n  }\n}\n"}' \
	> ${staking_address}.json
}

download

echo "id, epoch, reward_date, stake, stake_rewards" > ${staking_address}.csv
cat ${staking_address}.json | \
jq -r '.data.pt_addresses_history[] | [.id, .epoch, .ptepoch.reward_date, .stake, .stake_rewards] | @csv' \
>> ${staking_address}.csv
```

**Comment by papacarp** [comment]
this is done now.  please take a look and let me know of other formats we need to make for it.

**Comment by molecular** [comment]
@papacarp, thanks for implementing this!

I checked out the general format and it's perfect for my use-case (import into self-made tax db)

One remark: in general a unique identifier (like a primary key from your db) is very useful when syncing data between dbs. I guess in this case "epoch" could be used, but it may not be as safe as a primary key from your end.

And a question: At what point will 2021 data be available. I'm doing ongoing imports during the year and it seems I can only select 2020 at this point?

**Comment by papacarp** [comment]
I'll add both so you can start downloading data for 2021 as well.  I also
wanted to just have a date range option so you can pick your time periods.
I expect to get back onto pooltool with a lot more hours next week if our
catalyst fund thing gets approved.

**Comment by molecular** [comment]
@papacarp daterange would be nice, yes! Once you're at it, please consider an "all" button. It's not like we're talking tons of data, so it should be ok with server load?
