### ISSUE TITLE
block count errors

### ISSUE THREAD

**Issue by DanielEpstein** [papacarp/pooltool.io#9]
I notice when your pooltool node gets stuck and then recovers, epoch block count might fail to report the correct block count if a block was created at the time of your node being stuck

**Comment by papacarp** [comment]
Yes.  We keep track of all pools blocks AND slots.  We plan to implement a script to go back and validate the chain.  What happens is that when we process the blocks as they come in, if pooltool ends up on a dead end fork, some of the data is not right.  We have always planned to go back and validate (say from 50 blocks prior to the tip) but haven't done it yet.  We know this is leading to small errors in some of the pools block production stats.

**Comment by aftershowrc** [comment]
Came here to create a ticket but looks like your already aware 
![pooltool](https://user-images.githubusercontent.com/59306043/71929132-e4173800-3190-11ea-97b3-957d62787ff4.png)

**Comment by papacarp** [comment]
Please check your total counts.  We just synchronized to the tip

**Comment by cloudy-brain** [comment]
> Please check your total counts. We just synchronized to the tip

https://shelleyexplorer.cardano.org/en/stake-pool/2a58dedee661e07038dfa9fe98162330fdb43f3dd0d8a82b50ea6aaa360927b1/

Still a mismatch here

**Comment by cloudy-brain** [comment]
> > Please check your total counts. We just synchronized to the tip
> 
> https://shelleyexplorer.cardano.org/en/stake-pool/2a58dedee661e07038dfa9fe98162330fdb43f3dd0d8a82b50ea6aaa360927b1/
> 
> Still a mismatch here

Looks fixed now! Nice

**Comment by cloudy-brain** [comment]
> > > Please check your total counts. We just synchronized to the tip
> > 
> > 
> > https://shelleyexplorer.cardano.org/en/stake-pool/2a58dedee661e07038dfa9fe98162330fdb43f3dd0d8a82b50ea6aaa360927b1/
> > Still a mismatch here
> 
> Looks fixed now! Nice

Weird, looks off again.

**Comment by papacarp** [comment]
Pooltool jorm was stuck in an endless bootstrap this morning so it just caught up.   For now the plan is to re-validate all blocks once per epoch but will likely move to more of a continuous validation 10 blocks behind the tip (or maybe 20 blocks behind).  I haven't seen major rollbacks lately, but not sure I would notice if jorm is frequently rolling back by 20+ blocks.

**Comment by papacarp** [comment]
ok, all seem to be sync'd again

**Comment by Mixxaz** [comment]
Also seeing this issue but in the detailed view of my pool. I made 2 blocks last epoch but only showing one.
![Screenshot_20200120-082248](https://user-images.githubusercontent.com/58254786/72706586-af2abe00-3b5e-11ea-95ff-3dab226c7e4c.jpg)

**Comment by papacarp** [comment]
can you please check history now and let me know if we got that all sorted out.  all epoch totals should be validated now through epoch 44

**Comment by Mixxaz** [comment]
> can you please check history now and let me know if we got that all sorted out. all epoch totals should be validated now through epoch 44

Looks better to me.

**Comment by papacarp** [comment]
these should all be validated pretty much realtime now. closing it out.
